server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name aremhub.com www.aremhub.com 13.51.160.182;

    root /var/www/aremhub;
    index index.html;

    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        try_files $uri $uri/ /index.html;
    }
}
