server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name aremhub.com www.aremhub.com 98.84.138.59 _;

    ssl_certificate /etc/letsencrypt/live/aremhub.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aremhub.com/privkey.pem;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }
}
